### ISSUE TITLE
404 when using encapsulated-mdl

### ISSUE THREAD

**Issue by casalot** [genadis/aurelia-mdl#1]
I have downloaded the Aurelia Skeleton Navigation project, and followed the installation instructions from the aurelia-mdl README.

In the `app.hmtl` I have changed the code to the following:

``` html
<template>
  <require from="nav-bar.html"></require>
 <require from="encapsulated-mdl/material.amber-pink.min.css"></require>

  <nav-bar router.bind="router"></nav-bar>

</template>
```

When the app starts up, it throws a 404, not being able to find `encapsulated-mdl/material.amber-pink.min.cs`.

I have managed to overcome this by physically copying all the files from `jspm_packages/github/genadis/encapsulated-mdl@2.0.8` into `jspm_packages/github/genadis/aurelia-mdl@0.1.1`.

**Comment by genadis** [comment]
You shouldn't manually copy files. The error is because SystemJS doesn't know where to look for `encapsulated-mdl`.
Add something like `"encapsulated-mdl": "github:genadis/encapsulated-mdl@^2.0.8",` to your `package.json` jspm dependencies.
And run `jspm install/update` so it get's populated to your config.js file. You should see same line under `map` of of the `System.config`.

As an alternative use:

```
 <require from="../jspm_packages/github/genadis/encapsulated-mdl@2.0.8/material.amber-pink.min.css"></require>
```

But then you would have to update the versions in your app.html.

**Comment by casalot** [comment]
Thanks. Removing the manually copied files, and updating `package.json` with the dependency sorted this out.
