### ISSUE TITLE
Tabs - Failed to execute 'querySelector' on 'Element'

### ISSUE THREAD

**Issue by go4cas** [genadis/aurelia-mdl#11]
I'm using this definition for my tabs:

``` html
<div mdl="tabs" class="mdl-layout__tab-bar mdl-color--cyan-500 mdl-color-text--blue-grey-700 mdl-cell--hide-tablet mdl-cell--hide-phone">
    <a repeat.for="row of router.navigation | authFilter: isAuthenticated" class="mdl-layout__tab ${row.isActive ? 'is-active' : ''}" href.bind="row.href">${row.title}</a>
</div>
```

The idea is for each tab to redirect to one of my defined routes. When hovering over any of the tabs, I can see the correct URL in the browser footer. But, When clicking on a tab, I get the following error:

```
layout.js:444 Uncaught SyntaxError: Failed to execute 'querySelector' on 'Element': '#/config' is not a valid selector.
```

**Comment by genadis** [comment]
Unfortunately MDL tabs work locally on same page, it expects elements with id equal to href. Look [here](https://github.com/google/material-design-lite/blob/mdl-1.x/src/tabs/tabs.js#L145).

Please update if you find a workaround.

**Comment by chalu** [comment]
This also throws the same Uncaught DOMException: Failed to execute 'querySelector' on 'Element': '#!/scheduler' is not a valid selector when using MDL with Angular ui.router ui-sref="scheduler" on <a> element. This is because the <a> element is given href="#!/scheduler" ui.router which breaks MDL Tabs, as [it tries to query the DOM](https://github.com/google/material-design-lite/blob/mdl-1.x/src/tabs/tabs.js#L145) for element with ID of "!/schedule".
