### ISSUE TITLE
Will you be upgrading it to latest mdl?

### ISSUE THREAD

**Issue by Alexander-Taran** [genadis/aurelia-mdl#14]
If not please write up a short document on how to

**Comment by genadis** [comment]
Yes sure, I try to upgrade every 2/3 months. If there are important updates, drop a line and I can do it sooner.

Next update will be in about a week.

I'm staying on 1.x branch of the MDL, since the 2.x is in Alpha and will require rewrite of the patch (or will fix the need for it)

**Comment by genadis** [comment]
For upgrading by yourself, fork [encapsulated-mdl](https://github.com/genadis/encapsulated-mdl).
In the readme there is explanation of the patch. You can pull and merge the latest mdl.
Make sure to pull the 1.x branch. Most of the merges pretty simple since the patch is not intrusive.
Next  fork aurelia-mdl and change the MDL dependency to your mdl fork. 

```
    "dependencies": {
      "encapsulated-mdl": "github:genadis/encapsulated-mdl@^2.1.0"
    }
```

**Comment by Alexander-Taran** [comment]
Great. Thank you!!!

**Comment by genadis** [comment]
upgraded
