### ISSUE TITLE
Ability to extend `mdlTypes` to add support for custom MDL elements.

### ISSUE THREAD

**Issue by JoshMcCullough** [genadis/aurelia-mdl#15]
I'd like to be able to add an additional entry to `mdlTypes`. E.g. say we want to use [mdl-selectfield](https://github.com/mebibou/mdl-selectfield) as `<select mdl="select" ...>`. Is it possible currently?

**Comment by genadis** [comment]
I haven't tested it, but don't see immediate reason why not.
I've added the type to latest release (0.3,0)
You can try it as:
<div mdl="selectfield" ...>

Of course you will need to load the [mdl-selectfield](https://github.com/mebibou/mdl-selectfield) before the aurelia-mdl loads. Since it is not official MDL, I cannot add is dependency (just added it to known types).

Please report if it worked for you, so I can add note in README.

**Comment by JoshMcCullough** [comment]
Thanks, I'll give it a try.

**Comment by genadis** [comment]
@JoshMcCullough added support and documented [here](https://github.com/genadis/aurelia-mdl#adding-mdl-selectfield)
